"""Indexes

Revision ID: 5ab137c7b486
Revises: f8c50b35e0f7
Create Date: 2024-09-08 22:02:58.214197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ab137c7b486'
down_revision: Union[str, None] = 'f8c50b35e0f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('amazon_products_asin_key', 'amazon_products', type_='unique')
    op.create_index(op.f('ix_amazon_products_asin'), 'amazon_products', ['asin'], unique=True)
    op.alter_column('product_matches', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product_matches', 'amazon_product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_product_amazon_match', 'product_matches', ['product_id', 'amazon_product_id'], unique=True)
    op.drop_constraint('products_product_url_key', 'products', type_='unique')
    op.create_index(op.f('ix_products_product_url'), 'products', ['product_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_product_url'), table_name='products')
    op.create_unique_constraint('products_product_url_key', 'products', ['product_url'])
    op.drop_index('ix_product_amazon_match', table_name='product_matches')
    op.alter_column('product_matches', 'amazon_product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('product_matches', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_amazon_products_asin'), table_name='amazon_products')
    op.create_unique_constraint('amazon_products_asin_key', 'amazon_products', ['asin'])
    # ### end Alembic commands ###
