"""sellers

Revision ID: 5b41b294dc97
Revises: 16297fe744aa
Create Date: 2024-09-10 12:17:40.086213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b41b294dc97'
down_revision: Union[str, None] = '16297fe744aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amazon_products', sa.Column('amazon_buy_box_count', sa.Integer(), nullable=True))
    op.add_column('amazon_products', sa.Column('current_sellers', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('amazon_products', 'current_sellers')
    op.drop_column('amazon_products', 'amazon_buy_box_count')
    # ### end Alembic commands ###
