"""defaults

Revision ID: 62233ec2615b
Revises: 5ab137c7b486
Create Date: 2024-09-08 22:29:01.119087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62233ec2615b'
down_revision: Union[str, None] = '5ab137c7b486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amazon_products', sa.Column('created_date', sa.DateTime(), nullable=False))
    op.add_column('amazon_products', sa.Column('updated_date', sa.DateTime(), nullable=False))
    op.add_column('product_matches', sa.Column('created_date', sa.DateTime(), nullable=False))
    op.add_column('product_matches', sa.Column('updated_date', sa.DateTime(), nullable=False))
    op.add_column('products', sa.Column('created_date', sa.DateTime(), nullable=False))
    op.add_column('products', sa.Column('updated_date', sa.DateTime(), nullable=False))
    op.drop_column('products', 'sales_price')
    op.drop_column('products', 'regular_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('regular_price', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('sales_price', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('products', 'updated_date')
    op.drop_column('products', 'created_date')
    op.drop_column('product_matches', 'updated_date')
    op.drop_column('product_matches', 'created_date')
    op.drop_column('amazon_products', 'updated_date')
    op.drop_column('amazon_products', 'created_date')
    # ### end Alembic commands ###
