"""sellers

Revision ID: 8dd251168ad0
Revises: 5b41b294dc97
Create Date: 2024-09-10 14:37:28.371262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8dd251168ad0'
down_revision: Union[str, None] = '5b41b294dc97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('amazon_products', 'current_sellers',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('amazon_products', 'current_sellers',
               existing_type=sa.Integer(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    # ### end Alembic commands ###
