"""Initial migration

Revision ID: f8c50b35e0f7
Revises: 
Create Date: 2024-09-08 21:56:10.748710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c50b35e0f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amazon_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asin', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('product_url', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asin'),
    sa.UniqueConstraint('product_url')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('regular_price', sa.String(), nullable=False),
    sa.Column('sales_price', sa.String(), nullable=False),
    sa.Column('image_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('product_url', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_url')
    )
    op.create_table('product_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('amazon_product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['amazon_product_id'], ['amazon_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_matches')
    op.drop_table('products')
    op.drop_table('amazon_products')
    # ### end Alembic commands ###
